var huanshi=huanshi||{};huanshi.threemaps={};huanshi.threemaps.geometry={};huanshi.threemaps.utils={};huanshi.threemaps.terrain={};huanshi.threemaps.geometry.TileGeometry=function(a,b,d,c){THREE.Geometry.call(this);this._row=a;this._col=b;this._radius=c;this._zoomLevel=d;this._bound={N:0,W:0,E:0,S:0};this._latLng={lat:0,lng:0};this.metersPerPixel=function(a){return 2*this._radius*Math.PI/(Math.pow(2,a)*huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE)};this.calcBound=function(){var g=this.metersPerPixel(this._zoomLevel),c=Math.pow(2,this._zoomLevel)*huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE*g/2;this._bound.N=
a*huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE*g;this._bound.W=b*huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE*g;this._bound.N=c-this._bound.N;this._bound.W-=c;this._bound.E=this._bound.W+huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE*g;this._bound.S=this._bound.N-huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE*g};this._calcLatLng=function(a,c,b,d){this._latLng=huanshi.threemaps.utils.Mecator.toWgs84(a,c);b?this._latLng.lat=90:d&&(this._latLng.lat=-90)};this.createMesh=
function(){for(var a=Math.abs(this._bound.E-this._bound.W)/16,b=Math.pow(2,this._zoomLevel)-1,d=[],m=[],e=0;16>=e;e++){for(var h=[],l=[],f=0;16>=f;f++){this._calcLatLng(this._bound.W+f*a,this._bound.N-e*a,0==this._row&&0==e,this._row==b&&16==e);var k=new THREE.Vector3;k.x=c*Math.sin(this._latLng.lng*Math.PI/180)*Math.cos(this._latLng.lat*Math.PI/180);k.y=c*Math.sin(this._latLng.lat*Math.PI/180);k.z=c*Math.cos(this._latLng.lng*Math.PI/180)*Math.cos(this._latLng.lat*Math.PI/180);this.vertices.push(k);
h.push(this.vertices.length-1);l.push(new THREE.Vector2(f/16,1-e/16))}d.push(h);m.push(l)}for(e=0;16>e;e++)for(f=0;16>f;f++){var a=d[e][f+1],b=d[e][f],h=d[e+1][f],l=d[e+1][f+1],k=this.vertices[a].clone().normalize(),n=this.vertices[b].clone().normalize(),p=this.vertices[h].clone().normalize(),q=this.vertices[l].clone().normalize(),r=m[e][f+1].clone(),t=m[e][f].clone(),u=m[e+1][f].clone(),v=m[e+1][f+1].clone();Math.abs(this.vertices[a].y)===this._radius?(this.faces.push(new THREE.Face3(a,h,l,[k,p,
q])),this.faceVertexUvs[0].push([r,u,v])):Math.abs(this.vertices[h].y)===this._radius?(this.faces.push(new THREE.Face3(a,b,h,[k,n,p])),this.faceVertexUvs[0].push([r,t,u])):(this.faces.push(new THREE.Face3(a,b,l,[k,n,q])),this.faceVertexUvs[0].push([r,t,v]),this.faces.push(new THREE.Face3(b,h,l,[n,p,q])),this.faceVertexUvs[0].push([t.clone(),u,v.clone()]))}try{this.computeFaceNormals(),this.computeVertexNormals()}catch(w){console.error(w)}};this.calcBound();this.createMesh();this.boundingSphere=new THREE.Sphere(new THREE.Vector3,
this._radius)};huanshi.threemaps.geometry.TileGeometry.prototype=new THREE.Geometry;huanshi.threemaps.geometry.TileGeometry.prototype.constructor=huanshi.threemaps.TileGeometry;huanshi.threemaps.geometry.TileGeometry.PIXELS_PER_TILE=256;huanshi.threemaps.utils.Mecator={};huanshi.threemaps.utils.Mecator.PROJ_DST_PROJECTION="+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs";huanshi.threemaps.utils.Mecator._proj4=proj4(huanshi.threemaps.utils.Mecator.PROJ_DST_PROJECTION);huanshi.threemaps.utils.Mecator.toWgs84=function(a,b){var d=huanshi.threemaps.utils.Mecator._proj4.inverse([a,b]);return{lat:d[1],lng:d[0]}};huanshi.threemaps.earth=function(){this._radius=6378137;this._root=this._projector=this._camera=this._scene=this._renderer=this._container=null};
huanshi.threemaps.earth.prototype.init=function(a){a=a||{};this._container=a.container;this._renderer=new THREE.WebGLRenderer({antialias:!0});a=window.innerHeight-0;var b=window.innerWidth-0;this._renderer.setPixelRatio(window.devicePixelRatio);this._renderer.setSize(b,a);this._container.appendChild(this._renderer.domElement);this._scene=new THREE.Scene;this._camera=new THREE.PerspectiveCamera(45,b/a,1,10*this._radius);this._camera.position.z=5*this._radius;this._scene.add(this._camera);a=new THREE.DirectionalLight(16777215,
1.5);a.position.set(0,0,1);this._scene.add(a);this.createEarth();this._root=new THREE.Object3D;this._scene.add(this._root);this._projector=new THREE.Projector;this.initControls();this.run()};huanshi.threemaps.earth.prototype.createEarth=function(){for(var a=new THREE.Object3D,b=Math.pow(2,3),d=0;d<b;d++)for(var c=0;c<b;c++)a.add(this.createTile(d,c,3));this._scene.add(a)};
huanshi.threemaps.earth.prototype.createTile=function(a,b,d,c){c="http://mt3.google.cn/vt/lyrs=s@138&hl=zh-CN&gl=CN&src=app&x="+b+"&y="+a+"&z="+d+"&s=Galil";var g=new THREE.TextureLoader;g.crossOrigin="Anonymous";c=g.load(c);c=new THREE.MeshBasicMaterial({map:c});a=new huanshi.threemaps.geometry.TileGeometry(a,b,d,this._radius);return new THREE.Mesh(a,c)};huanshi.threemaps.earth.prototype.run=function(){this.update();this._renderer.render(this._scene,this._camera);var a=this;requestAnimationFrame(function(){a.run()})};
huanshi.threemaps.earth.prototype.update=function(){this._controls.update()};huanshi.threemaps.earth.prototype.initControls=function(){var a=new THREE.TrackballControls(this._camera,this._renderer.domElement),b=this._radius;a.rotateSpeed=1.5;a.zoomSpeed=3;a.panSpeed=.5;a.dynamicDampingFactor=.3;a.noZoom=!1;a.noPan=!1;a.staticMoving=!1;a.minDistance=1.1*b;a.maxDistance=10*b;this._controls=a;this._clock=new THREE.Clock};huanshi.threemaps.earth.prototype=new huanshi.threemaps.earth;
